version: "3"
services:
  frontend:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./frontend
    image: app-ui
    networks:
      - iot-light-app
  backend:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: app-api
    networks:
      - iot-light-app
    ports:
      - "1883:1883"
  nginx:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./nginx
    image: app-nginx
    ports:
      - "80:80"
    networks:
      - iot-light-app
networks:
  iot-light-app:
    driver: bridge
